from __future__ import annotations

from typing import Any, Iterator, overload

__version__: str

class CharsetMatch:
    def __init__(
        self,
        payload: bytes | bytearray,
        guessed_encoding: str,
        mean_mess_ratio: float,
        has_sig_or_bom: bool,
        languages: list[tuple[str, float]],
        decoded_payload: str | None = None,
        preemptive_declaration: str | None = None,
    ) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def add_submatch(self, other: CharsetMatch) -> None: ...
    def output(self, encoding: str = "utf_8") -> bytes: ...
    @property
    def encoding(self) -> str: ...
    @property
    def encoding_aliases(self) -> list[str]: ...
    @property
    def bom(self) -> bool: ...
    @property
    def byte_order_mark(self) -> bool: ...
    @property
    def languages(self) -> list[str]: ...
    @property
    def language(self) -> str: ...
    @property
    def chaos(self) -> float: ...
    @property
    def coherence(self) -> float: ...
    @property
    def percent_chaos(self) -> float: ...
    @property
    def percent_coherence(self) -> float: ...
    @property
    def multi_byte_usage(self) -> float: ...
    @property
    def raw(self) -> bytes | bytearray: ...
    @property
    def submatch(self) -> list[CharsetMatch]: ...
    @property
    def has_submatch(self) -> bool: ...
    @property
    def alphabets(self) -> list[str]: ...
    @property
    def could_be_from_charset(self) -> list[str]: ...
    @property
    def fingerprint(self) -> int: ...
    _string: str | None

class CharsetMatches:
    def __init__(self, results: list[CharsetMatch] | None = None) -> None: ...
    def __iter__(self) -> Iterator[CharsetMatch]: ...
    @overload
    def __getitem__(self, item: int) -> CharsetMatch: ...
    @overload
    def __getitem__(self, item: str) -> CharsetMatch: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def append(self, item: CharsetMatch) -> None: ...
    def best(self) -> CharsetMatch | None: ...
    def first(self) -> CharsetMatch | None: ...

class CliDetectionResult:
    def __init__(
        self,
        path: str,
        encoding: str | None,
        encoding_aliases: list[str],
        alternative_encodings: list[str],
        language: str,
        alphabets: list[str],
        has_sig_or_bom: bool,
        chaos: float,
        coherence: float,
        unicode_path: str | None,
        is_preferred: bool,
    ) -> None: ...
    path: str
    unicode_path: str | None
    encoding: str | None
    encoding_aliases: list[str]
    alternative_encodings: list[str]
    language: str
    alphabets: list[str]
    has_sig_or_bom: bool
    chaos: float
    coherence: float
    is_preferred: bool
    @property
    def __dict__(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

def backend_name() -> str: ...
def from_bytes(
    sequences: bytes | bytearray,
    steps: int = 5,
    chunk_size: int = 512,
    threshold: float = 0.2,
    cp_isolation: list[str] | None = None,
    cp_exclusion: list[str] | None = None,
    preemptive_behaviour: bool = True,
    explain: bool = False,
    language_threshold: float = 0.1,
    enable_fallback: bool = True,
) -> CharsetMatches: ...
def character_flags(character: str) -> int: ...
def unicode_range(character: str) -> str | None: ...
def is_suspiciously_successive_range(
    unicode_range_a: str | None, unicode_range_b: str | None
) -> bool: ...
def remove_accent(character: str) -> str: ...
def is_punctuation(character: str) -> bool: ...
def is_symbol(character: str) -> bool: ...
def is_emoticon(character: str) -> bool: ...
def is_separator(character: str) -> bool: ...
def is_case_variable(character: str) -> bool: ...
def is_unprintable(character: str) -> bool: ...
def any_specified_encoding(
    sequence: bytes | bytearray, search_zone: int = 8192
) -> str | None: ...
def should_strip_sig_or_bom(iana_encoding: str) -> bool: ...
def iana_name(cp_name: str, strict: bool = True) -> str: ...
def identify_sig_or_bom(sequence: bytes | bytearray) -> tuple[str | None, bytes]: ...
def is_cp_similar(iana_name_a: str, iana_name_b: str) -> bool: ...
def mb_encoding_languages(iana_name: str) -> list[str]: ...
def get_target_features(language: str) -> tuple[bool, bool]: ...
def alphabet_languages(
    characters: list[str], ignore_non_latin: bool = False
) -> list[str]: ...
def alpha_unicode_split(decoded_sequence: str) -> list[str]: ...
def coherence_ratio(
    decoded_sequence: str,
    threshold: float = 0.1,
    lg_inclusion: str | None = None,
) -> list[tuple[str, float]]: ...
def encoding_unicode_range(iana_name: str) -> list[str]: ...
def unicode_range_languages(primary_range: str) -> list[str]: ...
def encoding_languages(iana_name: str) -> list[str]: ...
def is_multi_byte_encoding(name: str) -> bool: ...
def cp_similarity(iana_name_a: str, iana_name_b: str) -> float: ...
def cut_sequence_chunks(
    sequences: bytes | bytearray,
    encoding_iana: str,
    offsets: range,
    chunk_size: int,
    bom_or_sig_available: bool,
    strip_sig_or_bom: bool,
    sig_payload: bytes,
    is_multi_byte_decoder: bool,
    decoded_payload: str | None = None,
    deferred_decoding: bool = False,
) -> list[str]: ...
def characters_popularity_compare(
    language: str, ordered_characters: list[str]
) -> float: ...
def merge_coherence_ratios(
    results: list[list[tuple[str, float]]],
) -> list[tuple[str, float]]: ...
def filter_alt_coherence_matches(
    results: list[tuple[str, float]],
) -> list[tuple[str, float]]: ...
def mess_ratio(
    decoded_sequence: str, maximum_threshold: float = 0.2, debug: bool = False
) -> float: ...
